# Week 1 - Discussion Section:
## Prey species in the California Drylands

## 1. Archive exploration

a. What is this data about?\
b. Is this data collected in situ by the authors or is it a synthesis of multiple datasets?\
c. During what time frame were the observations in the dataset collected?\
d. Does this dataset come with an associated metadata file?\
e. Does the dataset contain sensitive data?

#### Archive Data Summary

This dataset consists of a variety of environmental data (i.e. [WorldClim](www.worldclim.org), [MODIS and LPDAAC](https://lpdaac.usgs.gov/), [USGS](https://www.sciencebase.gov/catalog/item/542aebf9e4b057766eed286a), [census bureau's TIGER/Line](https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html) variables) related to arthropod prey species identified in the California drylands, originally noted by [Lortie et al. (2023)](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1002/2688-8319.12251). Data - collected from 1945 to 2022 - was downloaded from [GBIF](https://doi.org/10.15468/dl.ngym3r) on 14 Nov 2022 and cleaned in R (coordinateCleaner) prior to this dataset's publication. The dataset file - arth_prey_occurence_records_CA.csv - is accompanied by metadata csv and xml files. No sensitive data is included in this dataset.

#### Data Reference:

Rachel King, Jenna Braun, Michael Westphal, & CJ Lortie. (2023). Compiled occurrence records for prey items of listed species found in California drylands with associated environmental data. Knowledge Network for Biocomplexity. [doi:10.5063/F1VM49RH](https://knb.ecoinformatics.org/view/doi:10.5063/F1VM49RH).

## 2. Metadata exploration

In [4]:
import pandas as pd

# Load metadata csv file
url_meta = "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A3baf7289-bf90-4db3-ad11-58785c09b26e"
metadata_df = pd.read_csv(url_meta)

In [5]:
# Display list of dataset column descriptions
metadata_df.head()

  attribute                            description
0     class   taxonomic class of observed organism
1     order   taxonomic order of observed organism
2    family  taxonomic family of observed organism
3     genus                             genus name
4   species               full latin binomial name

## 3. Data Loading

In [8]:
# Load main dataset csv
url_main = "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A23d42528-1048-45d4-85d1-7e13b666e744"
prey = pd.read_csv(url_main)

In [9]:
# Confirm prey is a pandas.DataFrame
print(type(prey))

<class 'pandas.core.frame.DataFrame'>

In [11]:
# Display first rows of prey df
prey.head()

,class,order,family,genus,species,lat,long,eventDate,day,month,...,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,...,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,...,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,...,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,...,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,...,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104