# Week 1 - Discussion Section:
## Prey species in the California Drylands

## 1. Archive exploration

a. What is this data about?\
b. Is this data collected in situ by the authors or is it a synthesis of multiple datasets?\
c. During what time frame were the observations in the dataset collected?\
d. Does this dataset come with an associated metadata file?\
e. Does the dataset contain sensitive data?

#### Archive Data Summary

This dataset consists of a variety of environmental data (i.e. [WorldClim](www.worldclim.org), [MODIS and LPDAAC](https://lpdaac.usgs.gov/), [USGS](https://www.sciencebase.gov/catalog/item/542aebf9e4b057766eed286a), [census bureau's TIGER/Line](https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html) variables) related to arthropod prey species identified in the California drylands, originally noted by [Lortie et al. (2023)](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1002/2688-8319.12251). Data - collected from 1945 to 2022 - was downloaded from [GBIF](https://doi.org/10.15468/dl.ngym3r) on 14 Nov 2022 and cleaned in R (coordinateCleaner) prior to this dataset's publication. The dataset file - arth_prey_occurence_records_CA.csv - is accompanied by metadata csv and xml files. No sensitive data is included in this dataset.

#### Data Reference:

Rachel King, Jenna Braun, Michael Westphal, & CJ Lortie. (2023). Compiled occurrence records for prey items of listed species found in California drylands with associated environmental data. Knowledge Network for Biocomplexity. [doi:10.5063/F1VM49RH](https://knb.ecoinformatics.org/view/doi:10.5063/F1VM49RH).

## 2. Metadata exploration

In [1]:
import pandas as pd

# Load metadata csv file
url_meta = "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A3baf7289-bf90-4db3-ad11-58785c09b26e"
metadata_df = pd.read_csv(url_meta)

In [2]:
# Display list of dataset column descriptions
metadata_df.head()

  attribute                            description
0     class   taxonomic class of observed organism
1     order   taxonomic order of observed organism
2    family  taxonomic family of observed organism
3     genus                             genus name
4   species               full latin binomial name

## 3. Data Loading

In [3]:
# Load main dataset csv
url_main = "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A23d42528-1048-45d4-85d1-7e13b666e744"
prey = pd.read_csv(url_main)

In [4]:
# Confirm prey is a pandas.DataFrame
print(type(prey))

<class 'pandas.core.frame.DataFrame'>

## 4. Look at your data

In [6]:
# Display first rows of prey df
# prey
prey.head()

,class,order,family,genus,species,lat,long,eventDate,day,month,...,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,...,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,...,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,...,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,...,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,...,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104

In [7]:
# Some columns are hidden in this display
# See all columns w/
pd.set_option("display.max_columns", None)

In [8]:
prey.head()

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104

## 5. pd.DataFrame preliminary exploration

In [13]:
# Display first 5 rows
prey.head()

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104

In [12]:
# Display last 5 rows
prey.tail()

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
111151,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,33.660853,-115.721380,1980-04-10T00:00:00Z,10.0,4.0,1980,MCZ,3036.0,PRESERVED_SPECIMEN,1.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111152,200.539291,297.044373,111.539291,131.447403,21.313471,0.464611,50.358723,45.637127,7.404018,33.626942,44.287857,158.105041,43.560184,7319.267090,393.674744,34.807846,358.866913,217.827911,227.579758,0.925702,548.778870,barren,1187.127441
111152,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,35.933333,-116.716667,1998-03-26T00:00:00Z,26.0,3.0,1998,MCZ,NaN,PRESERVED_SPECIMEN,2.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111153,230.166946,344.166931,117.216942,49.012608,8.380343,1.000000,50.700531,21.778294,4.391233,9.430344,19.810688,163.872391,39.000000,8878.634766,442.558167,26.608175,415.950012,141.977646,273.793304,7.429875,-13.553053,grassland,792.632141
111153,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,34.156833,-118.726833,2010-05-21T00:00:00Z,21.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,40.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111154,161.271088,216.747421,116.372208,499.779816,106.116470,0.000000,96.797958,289.033630,4.470360,11.920360,279.654663,128.898209,53.252625,3962.391846,291.092560,51.291302,239.801269,118.917351,209.822205,2.387915,347.122986,grassland,4219.497559
111154,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,32.989167,-116.658500,2010-05-25T00:00:00Z,25.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,30.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111155,140.342300,217.269943,76.576256,559.577881,102.406273,3.000000,78.449997,293.045471,25.936378,36.503853,270.567810,154.063629,49.683960,5537.141602,315.901031,8.395161,307.505859,83.576256,199.928528,6.917791,981.674377,grassland,4865.626465
111155,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,36.251400,-117.731400,1992-09-02T00:00:00Z,2.0,9.0,1992,NTNU-VM,100000.0,PRESERVED_SPECIMEN,1.0,1bec5de3-758c-4ed2-ab13-1597601ad07a,111156,102.202797,197.274719,18.412592,294.105835,48.132629,6.007638,59.663151,133.747376,27.179491,31.660290,133.747376,141.080276,41.000000,7069.728027,293.179962,-47.896355,341.076324,20.241280,171.378082,23.553705,1913.307861,grassland,1628.940918

In [15]:
# Display column info
prey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111156 entries, 0 to 111155
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   class                          111156 non-null  object
 1   order                          111054 non-null  object
 2   family                         111156 non-null  object
 3   genus                          111156 non-null  object
 4   species                        111156 non-null  object
 5   lat                            111156 non-null  float64
 6   long                           111156 non-null  float64
 7   eventDate                      111156 non-null  object
 8   day                            110998 non-null  float64
 9   month                          111127 non-null  float64
 10  year                           111156 non-null  int64
 11  institutionCode                110414 non-null  object
 12  coordinateUncertaintyInMeters  84686 non-null   float64
 13  basisOfRecord                  111156 non-null  object
 14  individualCount                6351 non-null    float64
 15  datasetKey                     111156 non-null  object
 16  ID                             111156 non-null  int64
 17  bio1                           109629 non-null  float64
 18  bio10                          109629 non-null  float64
 19  bio11                          109629 non-null  float64
 20  bio12                          109629 non-null  float64
 21  bio13                          109629 non-null  float64
 22  bio14                          109629 non-null  float64
 23  bio15                          109629 non-null  float64
 24  bio16                          109629 non-null  float64
 25  bio17                          109629 non-null  float64
 26  bio18                          109629 non-null  float64
 27  bio19                          109629 non-null  float64
 28  bio2                           109629 non-null  float64
 29  bio3                           109629 non-null  float64
 30  bio4                           109629 non-null  float64
 31  bio5                           109629 non-null  float64
 32  bio6                           109629 non-null  float64
 33  bio7                           109629 non-null  float64
 34  bio8                           109629 non-null  float64
 35  bio9                           109629 non-null  float64
 36  dist                           109500 non-null  float64
 37  dem90_hf                       107765 non-null  float64
 38  lc_class                       106905 non-null  object
 39  ndvi                           109663 non-null  float64
dtypes: float64(28), int64(2), object(10)
memory usage: 33.9+ MB

In [17]:
# Display summary satistics (whole prey df)
prey.describe()

,lat,long,day,month,year,coordinateUncertaintyInMeters,individualCount,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,ndvi
count,111156.000000,111156.000000,110998.000000,111127.000000,111156.000000,84686.000000,6351.000000,111156.000000,109629.000000,109629.000000,109629.000000,109629.000000,109629.000000,109629.000000,109629.000000,109629.000000,109629.000000,109629.000000,109629.000000,109629.000000,109629.000000,109629.000000,109629.000000,109629.000000,109629.000000,109629.000000,109629.000000,109500.000000,107765.000000,109663.000000
mean,35.178718,-119.138205,16.062082,6.039414,2015.745457,3452.907316,6.184538,55578.500000,159.093569,216.264515,107.135167,445.669374,91.278456,1.269575,86.194109,244.366608,8.344888,15.516235,236.351363,127.784448,51.629836,4302.538588,293.196325,44.335932,248.860394,111.845109,206.869991,2.919556,317.230570,3772.240596
std,1.938925,2.098722,8.976351,2.745089,13.658433,9107.108465,206.072414,32088.117598,25.812052,32.688045,30.127505,189.641708,38.869389,1.849449,11.169015,99.939958,7.927973,11.794442,101.159281,23.464989,4.469225,1411.965747,45.587544,30.798850,59.995262,33.655644,27.419028,5.795438,464.443932,1340.255617
min,32.234538,-122.993000,1.000000,1.000000,1946.000000,1.000000,0.000000,1.000000,-6.819814,66.462288,-66.400551,49.012608,7.020388,0.000000,16.008331,19.061165,0.000000,1.021262,18.040777,61.709457,35.133366,1697.939697,145.801926,-123.342918,120.611740,-62.284061,37.847603,0.250821,-81.835320,-1435.728149
25%,33.780842,-121.633919,8.000000,4.000000,2018.000000,7.000000,1.000000,27789.750000,144.612976,197.583267,91.875648,316.210571,63.928646,0.000000,84.665176,177.131897,4.523281,9.010547,166.832077,110.970444,49.010860,3219.616699,261.654999,32.132576,200.322952,94.838722,190.591583,0.812508,52.636925,2905.856934
50%,34.173084,-118.372236,16.000000,6.000000,2020.000000,30.000000,1.000000,55578.500000,163.872009,217.598221,110.596123,412.921967,88.113831,1.000000,88.222641,238.913498,6.174775,11.950000,228.148666,126.989365,52.550823,3818.772949,287.514740,47.759235,235.655090,116.171745,209.837418,1.276386,148.975540,3687.899902
75%,37.334579,-117.383790,24.000000,8.000000,2021.000000,385.000000,1.000000,83367.250000,174.708221,231.707443,131.390717,540.643677,111.603882,1.486185,92.604401,296.644989,8.629289,16.535099,289.065887,144.741302,54.000000,5358.277832,320.777435,64.598259,299.841766,134.396210,224.861221,2.716769,363.470551,4483.013184
max,39.130568,-113.897000,31.000000,12.000000,2022.000000,100000.000000,16000.000000,111156.000000,237.939774,358.298737,144.572906,1481.367188,264.073852,21.658941,102.982521,727.951416,76.317703,112.839310,727.951416,192.134476,65.000000,9334.043945,455.314758,99.359131,425.640991,330.819061,325.276611,103.962555,3611.035156,8740.449219

In [19]:
# Display number of unique values in each column
prey.nunique()

class                                 4
order                                18
family                               63
genus                                92
species                              97
lat                               91909
long                              91965
eventDate                        102140
day                                  31
month                                12
year                                 77
institutionCode                      77
coordinateUncertaintyInMeters      4450
basisOfRecord                         4
individualCount                      42
datasetKey                           88
ID                               111156
bio1                              11778
bio10                             11981
bio11                             11803
bio12                             12117
bio13                             12020
bio14                              4586
bio15                             11848
bio16                             12102
bio17                              9243
bio18                             10698
bio19                             12095
bio2                              11915
bio3                               8723
bio4                              12110
bio5                              11992
bio6                              11934
bio7                              12088
bio8                              11889
bio9                              11980
dist                              11718
dem90_hf                          11904
lc_class                             12
ndvi                              29093
dtype: int64

In [20]:
# Display prey df shape (rows,columns)
prey.shape

(111156, 40)

In [21]:
# Display prey df column names
prey.columns

Index(['class', 'order', 'family', 'genus', 'species', 'lat', 'long',
       'eventDate', 'day', 'month', 'year', 'institutionCode',
       'coordinateUncertaintyInMeters', 'basisOfRecord', 'individualCount',
       'datasetKey', 'ID', 'bio1', 'bio10', 'bio11', 'bio12', 'bio13', 'bio14',
       'bio15', 'bio16', 'bio17', 'bio18', 'bio19', 'bio2', 'bio3', 'bio4',
       'bio5', 'bio6', 'bio7', 'bio8', 'bio9', 'dist', 'dem90_hf', 'lc_class',
       'ndvi'],
      dtype='object')

In [22]:
# Display column types
prey.dtypes

class                             object
order                             object
family                            object
genus                             object
species                           object
lat                              float64
long                             float64
eventDate                         object
day                              float64
month                            float64
year                               int64
institutionCode                   object
coordinateUncertaintyInMeters    float64
basisOfRecord                     object
individualCount                  float64
datasetKey                        object
ID                                 int64
bio1                             float64
bio10                            float64
bio11                            float64
bio12                            float64
bio13                            float64
bio14                            float64
bio15                            float64
bio16                            float64
bio17                            float64
bio18                            float64
bio19                            float64
bio2                             float64
bio3                             float64
bio4                             float64
bio5                             float64
bio6                             float64
bio7                             float64
bio8                             float64
bio9                             float64
dist                             float64
dem90_hf                         float64
lc_class                          object
ndvi                             float64
dtype: object